// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/config/default": {
            "get": {
                "description": "Get the default configuration template",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Get default configuration",
                "responses": {
                    "200": {
                        "description": "Default config retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to generate default config",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/config/load": {
            "post": {
                "description": "Load and validate a configuration from YAML data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Load configuration from YAML",
                "parameters": [
                    {
                        "description": "YAML data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Config loaded successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters or YAML parsing failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/config/validate": {
            "post": {
                "description": "Validate a configuration object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "Validate configuration",
                "parameters": [
                    {
                        "description": "Configuration object",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/autouiso_config.Config"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Config validation passed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Config validation failed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthz"
                ],
                "summary": "Health",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/index": {
            "get": {
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "home"
                ],
                "summary": "Home",
                "responses": {}
            }
        },
        "/iso/build/{id}/logs": {
            "get": {
                "description": "Get the logs of an ISO build process",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iso"
                ],
                "summary": "Get build logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Build logs retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Build ID cannot be empty",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Build ID does not exist",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/iso/build/{id}/status": {
            "get": {
                "description": "Get the status of an ISO build process",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iso"
                ],
                "summary": "Get build status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Build ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Build status retrieved successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Build ID cannot be empty",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Build ID does not exist",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/iso/generate": {
            "post": {
                "description": "Generate a new ISO image with the provided configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iso"
                ],
                "summary": "Generate ISO image",
                "parameters": [
                    {
                        "description": "ISO generation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/autouiso_api.GenerateISORequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ISO generation started",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to start ISO generation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/iso/upload": {
            "post": {
                "description": "Upload an ISO file to the server",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "iso"
                ],
                "summary": "Upload ISO file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "ISO file to upload",
                        "name": "iso",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ISO file uploaded successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Failed to upload ISO file",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/userdata/generate": {
            "post": {
                "description": "Generate a user-data configuration file based on provided config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-data"
                ],
                "summary": "Generate user-data configuration",
                "parameters": [
                    {
                        "description": "Configuration object",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/autouiso_config.Config"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User-data generated successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to generate user-data",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/userdata/preview": {
            "post": {
                "description": "Preview the user-data configuration that would be generated from a config object",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-data"
                ],
                "summary": "Preview user-data configuration",
                "parameters": [
                    {
                        "description": "Configuration object",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/autouiso_config.Config"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User-data preview generated successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid request parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to generate user-data preview",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "autouiso_api.GenerateISORequest": {
            "type": "object",
            "required": [
                "sourceType",
                "userData"
            ],
            "properties": {
                "codeName": {
                    "description": "Ubuntu release name (when sourceType is \"download\")",
                    "type": "string"
                },
                "destinationISO": {
                    "description": "Output ISO file path",
                    "type": "string"
                },
                "gpgVerify": {
                    "description": "Whether to perform GPG verification",
                    "type": "boolean"
                },
                "md5Checksum": {
                    "description": "Whether to update MD5 checksum",
                    "type": "boolean"
                },
                "packageList": {
                    "description": "Additional package list",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sourceISO": {
                    "description": "Local ISO file path (when sourceType is \"local\")",
                    "type": "string"
                },
                "sourceType": {
                    "description": "\"local\" or \"download\"",
                    "type": "string"
                },
                "useHWEKernel": {
                    "description": "Whether to use HWE kernel",
                    "type": "boolean"
                },
                "userData": {
                    "description": "user-data configuration content",
                    "type": "string"
                }
            }
        },
        "autouiso_config.AptConfig": {
            "type": "object",
            "properties": {
                "disable_components": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "disable_suites": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "geoip": {
                    "type": "boolean"
                },
                "preserve_sources_list": {
                    "type": "boolean"
                },
                "primary": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.PrimaryEntry"
                    }
                }
            }
        },
        "autouiso_config.Autoinstall": {
            "type": "object",
            "properties": {
                "apt": {
                    "$ref": "#/definitions/autouiso_config.AptConfig"
                },
                "drivers": {
                    "$ref": "#/definitions/autouiso_config.DriversConfig"
                },
                "identity": {
                    "$ref": "#/definitions/autouiso_config.Identity"
                },
                "kernel": {
                    "$ref": "#/definitions/autouiso_config.KernelConfig"
                },
                "keyboard": {
                    "$ref": "#/definitions/autouiso_config.KeyboardConfig"
                },
                "late-commands": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "locale": {
                    "type": "string"
                },
                "network": {
                    "$ref": "#/definitions/autouiso_config.NetworkConfig"
                },
                "packages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "shutdown": {
                    "type": "string"
                },
                "ssh": {
                    "$ref": "#/definitions/autouiso_config.SSHConfig"
                },
                "storage": {
                    "$ref": "#/definitions/autouiso_config.Storage"
                },
                "updates": {
                    "type": "string"
                },
                "user-data": {
                    "$ref": "#/definitions/autouiso_config.UserData"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "autouiso_config.Bond": {
            "type": "object",
            "properties": {
                "addresses": {
                    "description": "e.g., 192.168.1.10/24",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "critical": {
                    "type": "boolean"
                },
                "dhcp4": {
                    "type": "boolean"
                },
                "dhcp6": {
                    "type": "boolean"
                },
                "interfaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "link-local": {
                    "description": "e.g., [\"ipv4\", \"ipv6\", \"off\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "macaddress": {
                    "type": "string"
                },
                "match": {
                    "$ref": "#/definitions/autouiso_config.Match"
                },
                "mtu": {
                    "type": "integer"
                },
                "nameservers": {
                    "$ref": "#/definitions/autouiso_config.Nameservers"
                },
                "optional": {
                    "type": "boolean"
                },
                "parameters": {
                    "$ref": "#/definitions/autouiso_config.BondParams"
                },
                "routes": {
                    "description": "policy routes",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.Route"
                    }
                },
                "routing-policy": {
                    "description": "policy routing rules",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.RoutingPolicy"
                    }
                },
                "wakeonlan": {
                    "type": "boolean"
                }
            }
        },
        "autouiso_config.BondParams": {
            "type": "object",
            "properties": {
                "gratuitous-arp": {
                    "type": "integer"
                },
                "lacp-rate": {
                    "description": "fast/slow",
                    "type": "string"
                },
                "mii-monitor-interval": {
                    "type": "integer"
                },
                "min-links": {
                    "type": "integer"
                },
                "mode": {
                    "description": "active-backup, balance-rr, 802.3ad...",
                    "type": "string"
                },
                "primary": {
                    "type": "string"
                },
                "transmit-hash-policy": {
                    "type": "string"
                }
            }
        },
        "autouiso_config.Bridge": {
            "type": "object",
            "properties": {
                "addresses": {
                    "description": "e.g., 192.168.1.10/24",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "critical": {
                    "type": "boolean"
                },
                "dhcp4": {
                    "type": "boolean"
                },
                "dhcp6": {
                    "type": "boolean"
                },
                "interfaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "link-local": {
                    "description": "e.g., [\"ipv4\", \"ipv6\", \"off\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "macaddress": {
                    "type": "string"
                },
                "match": {
                    "$ref": "#/definitions/autouiso_config.Match"
                },
                "mtu": {
                    "type": "integer"
                },
                "nameservers": {
                    "$ref": "#/definitions/autouiso_config.Nameservers"
                },
                "optional": {
                    "type": "boolean"
                },
                "parameters": {
                    "$ref": "#/definitions/autouiso_config.BridgeParams"
                },
                "routes": {
                    "description": "policy routes",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.Route"
                    }
                },
                "routing-policy": {
                    "description": "policy routing rules",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.RoutingPolicy"
                    }
                },
                "wakeonlan": {
                    "type": "boolean"
                }
            }
        },
        "autouiso_config.BridgeParams": {
            "type": "object",
            "properties": {
                "ageing-time": {
                    "type": "integer"
                },
                "forward-delay": {
                    "type": "integer"
                },
                "priority": {
                    "type": "integer"
                },
                "stp": {
                    "type": "boolean"
                }
            }
        },
        "autouiso_config.Config": {
            "type": "object",
            "properties": {
                "autoinstall": {
                    "$ref": "#/definitions/autouiso_config.Autoinstall"
                }
            }
        },
        "autouiso_config.DiskMatch": {
            "type": "object",
            "properties": {
                "firmware_version": {
                    "type": "string"
                },
                "model": {
                    "description": "Disk model string (e.g., Samsung SSD 860)",
                    "type": "string"
                },
                "name": {
                    "description": "e.g. \"sda\"",
                    "type": "string"
                },
                "path": {
                    "description": "/dev/disk/by-path/...",
                    "type": "string"
                },
                "serial": {
                    "description": "serial number",
                    "type": "string"
                },
                "size": {
                    "description": "e.g. \"largest\", \"smallest\", \"100G\"",
                    "type": "string"
                },
                "wwn": {
                    "description": "World Wide Name",
                    "type": "string"
                }
            }
        },
        "autouiso_config.DriversConfig": {
            "type": "object",
            "properties": {
                "install": {
                    "type": "boolean"
                }
            }
        },
        "autouiso_config.DummyDevice": {
            "type": "object",
            "properties": {
                "addresses": {
                    "description": "e.g., 192.168.1.10/24",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "critical": {
                    "type": "boolean"
                },
                "dhcp4": {
                    "type": "boolean"
                },
                "dhcp6": {
                    "type": "boolean"
                },
                "link-local": {
                    "description": "e.g., [\"ipv4\", \"ipv6\", \"off\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "macaddress": {
                    "type": "string"
                },
                "match": {
                    "$ref": "#/definitions/autouiso_config.Match"
                },
                "mtu": {
                    "type": "integer"
                },
                "nameservers": {
                    "$ref": "#/definitions/autouiso_config.Nameservers"
                },
                "optional": {
                    "type": "boolean"
                },
                "routes": {
                    "description": "policy routes",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.Route"
                    }
                },
                "routing-policy": {
                    "description": "policy routing rules",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.RoutingPolicy"
                    }
                },
                "wakeonlan": {
                    "type": "boolean"
                }
            }
        },
        "autouiso_config.Ethernet": {
            "type": "object",
            "properties": {
                "addresses": {
                    "description": "e.g., 192.168.1.10/24",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "critical": {
                    "type": "boolean"
                },
                "dhcp4": {
                    "type": "boolean"
                },
                "dhcp6": {
                    "type": "boolean"
                },
                "link-local": {
                    "description": "e.g., [\"ipv4\", \"ipv6\", \"off\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "macaddress": {
                    "type": "string"
                },
                "match": {
                    "$ref": "#/definitions/autouiso_config.Match"
                },
                "mtu": {
                    "type": "integer"
                },
                "nameservers": {
                    "$ref": "#/definitions/autouiso_config.Nameservers"
                },
                "optional": {
                    "type": "boolean"
                },
                "routes": {
                    "description": "policy routes",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.Route"
                    }
                },
                "routing-policy": {
                    "description": "policy routing rules",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.RoutingPolicy"
                    }
                },
                "wakeonlan": {
                    "type": "boolean"
                }
            }
        },
        "autouiso_config.GrubConfig": {
            "type": "object",
            "properties": {
                "reorder_uefi": {
                    "type": "boolean"
                }
            }
        },
        "autouiso_config.Identity": {
            "type": "object",
            "properties": {
                "hostname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "realname": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "autouiso_config.KernelConfig": {
            "type": "object",
            "properties": {
                "package": {
                    "type": "string"
                }
            }
        },
        "autouiso_config.KeyboardConfig": {
            "type": "object",
            "properties": {
                "layout": {
                    "type": "string"
                },
                "toggle": {
                    "type": "string"
                },
                "variant": {
                    "type": "string"
                }
            }
        },
        "autouiso_config.Match": {
            "type": "object",
            "properties": {
                "driver": {
                    "type": "string"
                },
                "macaddress": {
                    "type": "string"
                },
                "name": {
                    "description": "glob supported, e.g., \"en*\"",
                    "type": "string"
                }
            }
        },
        "autouiso_config.Modem": {
            "type": "object",
            "properties": {
                "addresses": {
                    "description": "e.g., 192.168.1.10/24",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "apn": {
                    "type": "string"
                },
                "critical": {
                    "type": "boolean"
                },
                "dhcp4": {
                    "type": "boolean"
                },
                "dhcp6": {
                    "type": "boolean"
                },
                "link-local": {
                    "description": "e.g., [\"ipv4\", \"ipv6\", \"off\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "macaddress": {
                    "type": "string"
                },
                "match": {
                    "$ref": "#/definitions/autouiso_config.Match"
                },
                "mtu": {
                    "type": "integer"
                },
                "nameservers": {
                    "$ref": "#/definitions/autouiso_config.Nameservers"
                },
                "optional": {
                    "type": "boolean"
                },
                "pin": {
                    "type": "string"
                },
                "routes": {
                    "description": "policy routes",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.Route"
                    }
                },
                "routing-policy": {
                    "description": "policy routing rules",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.RoutingPolicy"
                    }
                },
                "wakeonlan": {
                    "type": "boolean"
                }
            }
        },
        "autouiso_config.NMDevice": {
            "type": "object",
            "properties": {
                "device": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "passthrough": {
                    "type": "object",
                    "additionalProperties": true
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "autouiso_config.Nameservers": {
            "type": "object",
            "properties": {
                "addresses": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "options": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "search": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "autouiso_config.NetworkConfig": {
            "type": "object",
            "properties": {
                "bonds": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/autouiso_config.Bond"
                    }
                },
                "bridges": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/autouiso_config.Bridge"
                    }
                },
                "dummy-devices": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/autouiso_config.DummyDevice"
                    }
                },
                "ethernets": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/autouiso_config.Ethernet"
                    }
                },
                "modems": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/autouiso_config.Modem"
                    }
                },
                "nm-devices": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/autouiso_config.NMDevice"
                    }
                },
                "renderer": {
                    "description": "network-renderer (e.g., \"networkd\", \"NetworkManager\")",
                    "type": "string"
                },
                "tunnels": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/autouiso_config.Tunnel"
                    }
                },
                "version": {
                    "type": "integer"
                },
                "vlans": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/autouiso_config.VLAN"
                    }
                },
                "vrfs": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/autouiso_config.VRF"
                    }
                },
                "wifis": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/autouiso_config.Wifi"
                    }
                }
            }
        },
        "autouiso_config.PrimaryEntry": {
            "type": "object",
            "properties": {
                "arches": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "autouiso_config.Route": {
            "type": "object",
            "properties": {
                "from": {
                    "description": "source prefix",
                    "type": "string"
                },
                "metric": {
                    "type": "integer"
                },
                "mtu": {
                    "type": "integer"
                },
                "on-link": {
                    "type": "boolean"
                },
                "table": {
                    "type": "integer"
                },
                "to": {
                    "description": "destination CIDR, or \"default\"",
                    "type": "string"
                },
                "type": {
                    "description": "e.g., \"unicast\" (rarely needed)",
                    "type": "string"
                },
                "via": {
                    "description": "next-hop",
                    "type": "string"
                }
            }
        },
        "autouiso_config.RoutingPolicy": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "fwmark": {
                    "type": "integer"
                },
                "priority": {
                    "type": "integer"
                },
                "table": {
                    "type": "integer"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "autouiso_config.SSHConfig": {
            "type": "object",
            "properties": {
                "allow-pw": {
                    "type": "boolean"
                },
                "authorized-keys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "install-server": {
                    "type": "boolean"
                }
            }
        },
        "autouiso_config.Storage": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.StorageConfig"
                    }
                },
                "grub": {
                    "$ref": "#/definitions/autouiso_config.GrubConfig"
                },
                "swap": {
                    "$ref": "#/definitions/autouiso_config.SwapConfig"
                }
            }
        },
        "autouiso_config.StorageConfig": {
            "type": "object",
            "properties": {
                "device": {
                    "type": "string"
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dm_name": {
                    "description": "For dm_crypt encryption",
                    "type": "string"
                },
                "flag": {
                    "type": "string"
                },
                "fstype": {
                    "description": "e.g. \"ext4\", \"btrfs\", \"xfs\"",
                    "type": "string"
                },
                "grub_device": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "key": {
                    "description": "For dm_crypt encryption",
                    "type": "string"
                },
                "keyfile": {
                    "description": "For dm_crypt encryption",
                    "type": "string"
                },
                "match": {
                    "$ref": "#/definitions/autouiso_config.DiskMatch"
                },
                "name": {
                    "type": "string"
                },
                "number": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "preserve": {
                    "type": "boolean"
                },
                "ptable": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "volgroup": {
                    "type": "string"
                },
                "volume": {
                    "type": "string"
                },
                "wipe": {
                    "description": "支持的选择类型: superblock, superblock-recursive, pvremove, zero, random",
                    "type": "string"
                }
            }
        },
        "autouiso_config.SwapConfig": {
            "type": "object",
            "properties": {
                "swap": {
                    "type": "integer"
                }
            }
        },
        "autouiso_config.Tunnel": {
            "type": "object",
            "properties": {
                "addresses": {
                    "description": "e.g., 192.168.1.10/24",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "critical": {
                    "type": "boolean"
                },
                "dhcp4": {
                    "type": "boolean"
                },
                "dhcp6": {
                    "type": "boolean"
                },
                "key": {
                    "description": "GRE key, optional",
                    "type": "integer"
                },
                "link-local": {
                    "description": "e.g., [\"ipv4\", \"ipv6\", \"off\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "local": {
                    "type": "string"
                },
                "macaddress": {
                    "type": "string"
                },
                "match": {
                    "$ref": "#/definitions/autouiso_config.Match"
                },
                "mode": {
                    "description": "gre, ipip, sit, gretap, etc.",
                    "type": "string"
                },
                "mtu": {
                    "type": "integer"
                },
                "nameservers": {
                    "$ref": "#/definitions/autouiso_config.Nameservers"
                },
                "optional": {
                    "type": "boolean"
                },
                "port": {
                    "description": "if applicable",
                    "type": "integer"
                },
                "remote": {
                    "type": "string"
                },
                "routes": {
                    "description": "policy routes",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.Route"
                    }
                },
                "routing-policy": {
                    "description": "policy routing rules",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.RoutingPolicy"
                    }
                },
                "ttl": {
                    "type": "integer"
                },
                "wakeonlan": {
                    "type": "boolean"
                }
            }
        },
        "autouiso_config.UserData": {
            "type": "object",
            "properties": {
                "runcmd": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "autouiso_config.VLAN": {
            "type": "object",
            "properties": {
                "addresses": {
                    "description": "e.g., 192.168.1.10/24",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "critical": {
                    "type": "boolean"
                },
                "dhcp4": {
                    "type": "boolean"
                },
                "dhcp6": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "link": {
                    "description": "parent interface",
                    "type": "string"
                },
                "link-local": {
                    "description": "e.g., [\"ipv4\", \"ipv6\", \"off\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "macaddress": {
                    "type": "string"
                },
                "match": {
                    "$ref": "#/definitions/autouiso_config.Match"
                },
                "mtu": {
                    "type": "integer"
                },
                "nameservers": {
                    "$ref": "#/definitions/autouiso_config.Nameservers"
                },
                "optional": {
                    "type": "boolean"
                },
                "routes": {
                    "description": "policy routes",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.Route"
                    }
                },
                "routing-policy": {
                    "description": "policy routing rules",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.RoutingPolicy"
                    }
                },
                "wakeonlan": {
                    "type": "boolean"
                }
            }
        },
        "autouiso_config.VRF": {
            "type": "object",
            "properties": {
                "interfaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "routes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.Route"
                    }
                },
                "routing-policy": {
                    "description": "Policy routing specific to this VRF",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.RoutingPolicy"
                    }
                },
                "table": {
                    "type": "integer"
                }
            }
        },
        "autouiso_config.Wifi": {
            "type": "object",
            "properties": {
                "access-points": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/autouiso_config.WifiAP"
                    }
                },
                "addresses": {
                    "description": "e.g., 192.168.1.10/24",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "critical": {
                    "type": "boolean"
                },
                "dhcp4": {
                    "type": "boolean"
                },
                "dhcp6": {
                    "type": "boolean"
                },
                "link-local": {
                    "description": "e.g., [\"ipv4\", \"ipv6\", \"off\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "macaddress": {
                    "type": "string"
                },
                "match": {
                    "$ref": "#/definitions/autouiso_config.Match"
                },
                "mtu": {
                    "type": "integer"
                },
                "nameservers": {
                    "$ref": "#/definitions/autouiso_config.Nameservers"
                },
                "optional": {
                    "type": "boolean"
                },
                "routes": {
                    "description": "policy routes",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.Route"
                    }
                },
                "routing-policy": {
                    "description": "policy routing rules",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/autouiso_config.RoutingPolicy"
                    }
                },
                "wakeonlan": {
                    "type": "boolean"
                }
            }
        },
        "autouiso_config.WifiAP": {
            "type": "object",
            "properties": {
                "auth": {
                    "description": "backend-specific, rarely used",
                    "type": "string"
                },
                "band": {
                    "description": "e.g., \"2.4GHz\", \"5GHz\"",
                    "type": "string"
                },
                "bssid": {
                    "description": "AP MAC, optional",
                    "type": "string"
                },
                "channel": {
                    "type": "integer"
                },
                "client-auth": {
                    "description": "tls/wpa-enterprise etc. (simplified)",
                    "type": "string"
                },
                "hidden": {
                    "type": "boolean"
                },
                "mode": {
                    "description": "e.g., \"infrastructure\"",
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
